<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Daily Sales Report</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            line-height: 1.6;
            color: #333;
            max-width: 800px;
            margin: 0 auto;
            padding: 20px;
        }
        .header {
            background: #2563eb;
            color: white;
            padding: 20px;
            border-radius: 8px;
            margin-bottom: 20px;
        }
        .summary {
            background: #f3f4f6;
            padding: 15px;
            border-radius: 8px;
            margin-bottom: 20px;
        }
        .summary-item {
            display: flex;
            justify-content: space-between;
            padding: 8px 0;
            border-bottom: 1px solid #e5e7eb;
        }
        .summary-item:last-child {
            border-bottom: none;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }
        th, td {
            padding: 12px;
            text-align: left;
            border-bottom: 1px solid #e5e7eb;
        }
        th {
            background: #f9fafb;
            font-weight: bold;
        }
        .footer {
            margin-top: 30px;
            padding-top: 20px;
            border-top: 1px solid #e5e7eb;
            text-align: center;
            color: #6b7280;
            font-size: 12px;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>Daily Sales Report</h1>
        <p>{{ $reportDate->format('F d, Y') }}</p>
    </div>

    <div class="summary">
        <h2>Summary</h2>
        <div class="summary-item">
            <span><strong>Total Transactions:</strong></span>
            <span>{{ $totals['total_transactions'] }}</span>
        </div>
        <div class="summary-item">
            <span><strong>Total Revenue:</strong></span>
            <span>KES {{ number_format($totals['total_amount'], 2) }}</span>
        </div>
        <div class="summary-item">
            <span><strong>Subtotal:</strong></span>
            <span>KES {{ number_format($totals['total_subtotal'], 2) }}</span>
        </div>
        <div class="summary-item">
            <span><strong>Tax:</strong></span>
            <span>KES {{ number_format($totals['total_tax'], 2) }}</span>
        </div>
        <div class="summary-item">
            <span><strong>Discount:</strong></span>
            <span>KES {{ number_format($totals['total_discount'], 2) }}</span>
        </div>
        <div class="summary-item">
            <span><strong>Average Sale:</strong></span>
            <span>KES {{ number_format($totals['avg_sale'], 2) }}</span>
        </div>
    </div>

    @if($sales->count() > 0)
    <h2>Sales Details</h2>
    <table>
        <thead>
            <tr>
                <th>Invoice #</th>
                <th>Date</th>
                <th>Customer</th>
                <th>Items</th>
                <th style="text-align: right;">Amount</th>
            </tr>
        </thead>
        <tbody>
            @foreach($sales as $sale)
            <tr>
                <td>{{ $sale->invoice_number }}</td>
                <td>{{ $sale->date->format('M d, Y H:i') }}</td>
                <td>{{ $sale->customer ? $sale->customer->name : 'Walk-in' }}</td>
                <td>{{ $sale->saleItems->count() }} items</td>
                <td style="text-align: right;">KES {{ number_format($sale->total_amount, 2) }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>
    @else
    <p>No sales recorded for this date.</p>
    @endif

    <div class="footer">
        <p>This is an automated report generated by {{ config('app.name', 'Wine Not') }}</p>
    </div>
</body>
</html>

