<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>URGENT: Low Stock Alert</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            line-height: 1.6;
            color: #333;
            max-width: 800px;
            margin: 0 auto;
            padding: 20px;
        }
        .header {
            background: #dc2626;
            color: white;
            padding: 20px;
            border-radius: 8px;
            margin-bottom: 20px;
        }
        .alert {
            background: #fee2e2;
            border-left: 4px solid #dc2626;
            padding: 15px;
            margin-bottom: 20px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }
        th, td {
            padding: 12px;
            text-align: left;
            border-bottom: 1px solid #e5e7eb;
        }
        th {
            background: #f9fafb;
            font-weight: bold;
        }
        .low-stock {
            color: #dc2626;
            font-weight: bold;
        }
        .footer {
            margin-top: 30px;
            padding-top: 20px;
            border-top: 1px solid #e5e7eb;
            text-align: center;
            color: #6b7280;
            font-size: 12px;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>🚨 URGENT: Low Stock Alert</h1>
        <p>{{ now()->format('F d, Y H:i') }}</p>
    </div>

    <div class="alert">
        <h2>⚠️ Immediate Action Required</h2>
        <p><strong>{{ $lowStockItems->count() }} item(s)</strong> are below their reorder level and need immediate attention.</p>
    </div>

    <table>
        <thead>
            <tr>
                <th>SKU</th>
                <th>Item Name</th>
                <th>Category</th>
                <th style="text-align: right;">Current Stock</th>
                <th style="text-align: right;">Reorder Level</th>
                <th>Status</th>
            </tr>
        </thead>
        <tbody>
            @foreach($lowStockItems as $item)
            <tr>
                <td>{{ $item->sku ?? 'N/A' }}</td>
                <td>{{ $item->name }}</td>
                <td>{{ $item->category->name ?? 'N/A' }}</td>
                <td style="text-align: right;" class="low-stock">{{ $item->stock_quantity }}</td>
                <td style="text-align: right;">{{ $item->reorder_level }}</td>
                <td class="low-stock">⚠️ Low Stock</td>
            </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        <p>This is an automated alert generated by {{ config('app.name', 'Wine Not') }}</p>
        <p>Please take immediate action to restock these items.</p>
    </div>
</body>
</html>

